version: '3.8'

services:
  pokeslot:
    build: .
    # Only expose frontend port internally
    expose:
      - "5000"
      - "5001"
    volumes:
      - pokeslot_data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/pokeslot.db
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pokeslot_network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-vps.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pokeslot
    restart: unless-stopped
    networks:
      - pokeslot_network

volumes:
  pokeslot_data:
    driver: local

networks:
  pokeslot_network:
    driver: bridge